### ISSUE TITLE
Invalid Conversion

### ISSUE THREAD

**Issue by wwderw** [RobLoach/raylib-aseprite#19]
Using Raylib 4.5, I'm getting an invalid conversion with the header file.

`invalid conversion from void* to Texture2D*` on 220:38.

**Comment by RobLoach** [comment]
Just added a cast. Mind trying again?

**Comment by wwderw** [comment]
It built that time.  Seems to be good, should know more when I get back to the project later on.

Thanks!

**Comment by RobLoach** [comment]
Great to hear. Thanks for checking it out
