### ISSUE TITLE
Raylib 5.0?

### ISSUE THREAD

**Issue by Lucas-Marcel** [RobLoach/raylib-aseprite#21]

**Comment by RobLoach** [comment]
Should work without any changes. If you submit a PR with the update, I'd be happy to merge.

**Comment by Lucas-Marcel** [comment]
By the way, thanks for the awesome header.

**Comment by RobLoach** [comment]
Thanks for checking it out! And most of the credit should go towards cute_aseprite :wink: ... Would love to actually target raylib 5 tho, so would apppreciate any help there

**Comment by Lucas-Marcel** [comment]
It has been working so far, no issues for now, the only thing missing is a mirror/flip method. I'm gonna try to do that by myself.
