### ISSUE TITLE
Flip AsepriteTag

### ISSUE THREAD

**Issue by wwderw** [RobLoach/raylib-aseprite#23]
Is it possible to  flip vertical/horizontal asepritetags, akin to the ImageFlipVertical() etc functionality in Raylib?

**Comment by RobLoach** [comment]
Could replicate a lot of the DrawTexture functions. Mind putting together a PR?

**Comment by wwderw** [comment]
I'm one of those that just knows enough to cause damage.  Any PR that I create would definitely not be a thing of beauty.
